### ISSUE TITLE
Ajout nouv commande : group list

### ISSUE THREAD

**Issue by TobiBiotex** [Chasseur-de-Succes/CDS-BOT#108]
Ajouter une commande qui retourne une liste condensé des groupes actif (trié par le nom du jeu ?)
commande : group list
_Suggestion de Domarkius_

**Comment by rick-gnous** [comment]
Je vois pas trop l'intérêt de ce genre de commandes. Un utilisateur n'a pas besoin de voir tous les groupes qui existent. Souvent, les groupes sont fait entre joueurs après une discussion, une personne externe ne va pas se greffer dessus.
