### ISSUE TITLE
[Sqweeb] Possibilité feedback fin de groupe

### ISSUE THREAD

**Issue by TobiBiotex** [Chasseur-de-Succes/CDS-BOT#112]
> _À chaque fin d'event une fois que la personne fait /dissolve ou /end un message apparaît au chef du groupe et lui demande comment c'est passé l'évent, il aura la possibilité de répondre si y a un pb ou ne pas répondre, et le message sera envoyé a un salon admin_

**Comment by rick-gnous** [comment]
On se concentre sur une version envoie et oublie, pas besoin de garder le message en base. Le bot sert de proxy.

**Comment by rick-gnous** [comment]
Duplica #66
