### ISSUE TITLE
[Sqweeb] système de ticket

### ISSUE THREAD

**Issue by TobiBiotex** [Chasseur-de-Succes/CDS-BOT#113]
> J'ai rêvé que le bot avec une commande /problem mp le gars qui a un pb, explique le pb et le message et envoyé aux salon admin ( permettant aux admins de ne pas être spammer au moindre ouin ouin)

**Comment by rick-gnous** [comment]
Peut-être plus intéressant de recopier le système d'autres bots : un salon vide avec juste un bouton généré par le bot. Quand on clique dessus, ça crée un salon privé avec les admins et l'utilisateur. Le bot garde un message avec un bouton pour fermer le salon (ou le supprimer ?)

**Comment by Kekwel** [comment]
ah bonne idée, j'avais pensé aux forums mais un salon privé c'est ptete mieux pour n'autoriser que les admins et la personne concernée

**Comment by 0xN0x** [comment]
Je propose que je le fasse.

Plus précisément faire un bouton ou une commande, peu importe ça ne change rien niveau code, qui ouvrira une modal demandant un titre au ticket ainsi que le contenu du ticket en question, à l'envoi un channel sera créé dans une catégorie faite pour, chaque channel est visible par le staff ainsi que le créateur du ticket, deux bouton seront disponible dans le channel en épinglé : Résolu et Clore pour indiquer que le problème a été résolu ou n'a pas de solution/est un non-problème.

Le titre et contenu du message seront remis dans le channel et épinglés eux aussi. Tout le monde pourra résoudre le ticket y compris son auteur dans le cas ou la solution est trouvé par lui même, la cloture du ticket ne sera faisable que par le staff.

La ou une question se pose c'est sur l'archivage des tickets : 
  - La solution la plus simple est de retirer la permission de l'utilisateur à voir le channel, puis déplacer le channel dans une seconde catégorie faite pour les tickets archivés.
  - Une autre solution plus compliquée est de récupérer la liste et le contenu de l'échange, et en faire une image de la conversation qui sera posté dans les logs en l'état (il faudra peut être passer par un tiers pour l'upload à cause de la compression de Discord qui risque de rendre illisible une telle image).

**Comment by rick-gnous** [comment]
On va se pencher sur le sujet de la préservation des tickets. Ça va être tendu de garder en archive tout parce qu'on est limité en termes de nombre de salons. Au lieu de garder ou de faire un screen, peut-être faire une retranscription dans le salon log ?

**Comment by 0xN0x** [comment]
Retranscription je pense que c'est tout à fait possible, mais faut se poser la question des images dans ce cas là

**Comment by rick-gnous** [comment]
A creuser en effet. Sinon le bot peut peut-être copier coller les photos ?
Je pense qu'il faut aussi faire un nouveau salon log, avec par ex. pour nom `log-tickets` pour les retrouver plus facilement.

**Comment by Kekwel** [comment]
ok pour moi !

**Comment by Kekwel** [comment]
Et quand est-il des fils (threads) ou même un forum plutôt que des salons ? J'ai pas encore cherché si c'était possible de limiter à certains users l'accès aux forum (les threads oui)

**Comment by 0xN0x** [comment]
Thread comme forum il sera pas possible de limiter par utilisateur

**Comment by 0xN0x** [comment]
Pour les threads comme pour les forums au dernières nouvelles il n'est pas possible de donner des permissions par thread ou par post

**Comment by Kekwel** [comment]
Pour les threads, c'est bien possible : 
https://support.discord.com/hc/en-us/articles/4403205878423-Threads-FAQ#h_01FBQZH4F0E9RX2K078Y6EG6QB
https://discordjs.guide/popular-topics/threads.html#public-and-private-threads
![image](https://github.com/Chasseur-de-Succes/CDS-BOT/assets/9060357/14c003ac-2536-46d1-ae36-c736d4f4251a)

**Comment by 0xN0x** [comment]
Oooh, effectivement je savais pas du tout, ça en fait un bien meilleur système pour les tickets alors car ce sera archivé directement par Discord
Je vais surement partir là dessus plutôt du coup, merci 🙂

**Comment by 0xN0x** [comment]
Ce qui est fait pour le moment : 

- [X] Commande `/ticket` pour créer un ticket
- [X] Création d'un thread dans le channel de ticket
- [X] Envoi d'un message dans le thread avec le titre et le contenu du ticket ainsi qu'un bouton pour clore le ticket
- [X] Ajout du créateur du ticket et de tous les utilisateurs avec la permissions `Administrator` au thread
- [X] Réception de l'interaction avec le bouton pour envoyer un message dans le thread pour préciser qui a clos le thread et quand puis lock et archivage du thread

Il me reste plus qu'à mettre le tout un peu plus au propre et ce sera bon, tout est géré directement dans le `interactionCreate` pour éviter des collecteurs, je vais voir ce qui serait le mieux pour diviser tout ça en plusieurs fichiers car on va vite se retrouver à avoir un fichier d'event gigantesque sinon lors des refactors.
