### ISSUE TITLE
[Sqweeb] [Commande] limiter nb personnes dans voc

### ISSUE THREAD

**Issue by TobiBiotex** [Chasseur-de-Succes/CDS-BOT#114]
> Que le bot pouvait fermer un salon vocal lorsque tous les membres du groupe de l'event s'y trouve, pour éviter que d'autre personne n'y rentre, en faisant une commande par le créateur du salon

**Comment by rick-gnous** [comment]
Est-ce que le bot ne créerait pas un salon avec pil poil la limitation s'il voit que c'est un chef + heure d'un événement ? Sinon on peut juste faire une commande `lock` qui set la limite. On oublie ensuite ce salon, pas besoin de modifier la base pour.

**Comment by Kekwel** [comment]
Je trouve cette suggestion assez restrictif en la relisant en fait
Et ca rajoute des actions à faire par le capitaine du groupe

**Comment by rick-gnous** [comment]
A voir avec sqweeb mais ça me semble en effet assez restrictif pour pas grand chose au final. Je doute que beaucoup de personnes viennent polluer les vocaux des groupes.

**Comment by rick-gnous** [comment]
Il n'y a pas eu d'abus pour le moment, on ferme ce ticket et on peut le réouvrir en cas de besoin plus tard
