### ISSUE TITLE
[Sqweeb] limitation nbr de groupe

### ISSUE THREAD

**Issue by TobiBiotex** [Chasseur-de-Succes/CDS-BOT#115]
> J'ai rêvé oui je rêve beaucoup, que le bot puisse mettre une limite de participation aux events! " Tu es actuellement sur 5 events, finis les autres avant de t'inscrire à d'autre, si tu penses être capable de participer  plus d'event, contact un admin"
> et pareil pour les créations de groupe: " Tu as  crée 5 groupes, finis en un   ou ferme en un"
>  un truc du genre

**Comment by rick-gnous** [comment]
Ajout d'une variable d'environnement pour ça. Il faudrait aussi modifier la base pour pouvoir tracker les changements du nombre max (ou alors les admins rajoutent a la main les gens dans le groupe ? Il y a une commande pour ça ?)

**Comment by Kekwel** [comment]
Tu parle du nb max de groupe simultanément ? Pk tracker le changement ?
et y a pas de commande pour "forcer" le join dans un groupe. ca peut se faire

**Comment by rick-gnous** [comment]
Pour permettre a des utilisateurs d'avoir accès a plus de groupes. Je pense cependant que l'ajout d'une commande pour mettre quelqu'un dans un groupe est mieux pour éviter que ça reste après, si c'est exceptionnel a un instant T.
