### ISSUE TITLE
ID développeurs

### ISSUE THREAD

**Issue by rick-gnous** [Chasseur-de-Succes/CDS-BOT#118]
A mettre plutôt dans le fichier de configuration, permet une gestion plus souple s'il faut en ajouter ou en retirer.

**Comment by Kekwel** [comment]
Après il me semble que c'est utilisé seulement dans la commande /info, donc pas vraiment le plus utile !

**Comment by rick-gnous** [comment]
Bien sûr, mais ça sera plus simple et propre avec un fichier à côté. Ça reste pas urgent par rapport a d'autres tickets

**Comment by Kekwel** [comment]
Et surtout, si l'un des dev n'est pas présent sur le serveur où est le bot (sur mon discord où je test mon bot en local par exemple ^^), la commande /info ne fonctionne pas car, dans le fichier [slash-commands/info.js ](https://github.com/Chasseur-de-Succes/CDS-BOT/blob/c83dfc3a4c1246bca75f5ee5c62d7bd08f372c0e/slash_commands/info.js#L19) :
```js
const Tobi = client.users.cache.get("229312422043713537");
const Kekwel = client.users.cache.get("283681024360054785");
const Rick = client.users.cache.get("163697401935298560");
```

**Comment by 0xN0x** [comment]
> Et surtout, si l'un des dev n'est pas présent sur le serveur où est le bot (sur mon discord où je test mon bot en local par exemple ^^), la commande /info ne fonctionne pas car, dans le fichier [slash-commands/info.js ](https://github.com/Chasseur-de-Succes/CDS-BOT/blob/c83dfc3a4c1246bca75f5ee5c62d7bd08f372c0e/slash_commands/info.js#L19) :
> 
> ```js
> const Tobi = client.users.cache.get("229312422043713537");
> const Kekwel = client.users.cache.get("283681024360054785");
> const Rick = client.users.cache.get("163697401935298560");
> ```

Pour ça il faudra surtout rework la commande en passant pour supporter qu'un utilisateur puisse ne pas être trouvé (ça évitera aussi de planter le bot en boucle à l'utilisation si un jour une des personnes de la liste quitte le serveur et qu'une update n'est pas faite directement.
