### ISSUE TITLE
Utilisation de boutons pour rejoindre ou quitter le groupe

### ISSUE THREAD

**Issue by rick-gnous** [Chasseur-de-Succes/CDS-BOT#122]
Plutot utiliser un bouton au lieu d'une réaction pour pouvoir rejoindre le groupe : plus beau et permet d'éviter certains MPs (cf. #75)

**Comment by rick-gnous** [comment]
Utilisation pour les IDs: `join-id_group` et `leave-id_group`

**Comment by 0xN0x** [comment]
@rick-gnous `group-123456789-join` ne serait pas plus cohérent ?
Pour avoir un id dans ce format : `<catégorie>-<identifiant unique>-<action>` dans tous les cas.

Comme ça si vous avez d'autres interactions avec id par la suite qui ont besoin de join ou leave vous pouvez les utiliser aussi sans avoir de noms à rallonge pour l'identifier

**Comment by rick-gnous** [comment]
Je pense que c'est une meilleure idée en effet

**Comment by Kekwel** [comment]
avec l'utilisation des réponses éphémères (faut que je retire encore l'emoji de réaction, mais la dodo 😴)
![image](https://github.com/Chasseur-de-Succes/CDS-BOT/assets/9060357/06f0df46-32a1-46c3-b97b-68f92d6dc9f1)

**Comment by rick-gnous** [comment]
Peut-être désactiver le bouton rejoindre une fois que le groupe est complet :thinking: 
Je sais aussi que Nox a de très bonnes idées pour les boutons et le refactor de code derrière, il jettera peut-être un oeil à la PR afin de l'améliorer aussi

**Comment by Kekwel** [comment]
yes j'y ai pensé aussi pour désactiver le bouton, 00h15 c'est déjà tard pour moi ^^

**Comment by 0xN0x** [comment]
Yep j'avais fais une implementation fonctionnelle aussi mais j'avais oublié de prévenir donc c'est mb, après j'avais vraiment plug à la place du collecteur actuel pour les réactions, j'avais pas trop refactor donc il doit pas y avoir grand chose de différents.

A terme faudra passer par le interactionCreate plutôt pour éviter d'avoir besoin de recréer des collector à chaque lancement du bot avec le `loader.js`, ça fera moins de taux d'erreur.

Faudra aussi voir pour utiliser justement le loader actuel pour refaire une passe sur toutes les anciennes annonces de groupes pour retirer la réactions et rajouter les boutons, à réfléchir pour l'implem par contre j'ai pas forcément d'idée propre même si c'est un one shot pour le premier lancement avec les boutons.
Peut être que faire juste un script a coté du bot serait presque plus propre.

**Comment by 0xN0x** [comment]
```js
/**
 * Créer un collecteur de réactions pour les messages Groupes
 * Si l'on clique sur la reaction, on s'ajoute au groupe (ssi on y est pas déjà et qu'on est pas le capitaine)
 * Sinon on se retire du groupe (sauf si on est le capitaine)
 * @param {*} client 
 * @param {*} msg le message
 * @param {*} grp le groupe provenant de la bdd
 */
 async function createReactionCollectorGroup(client, msg, grp) {
    // Create interactions collector for Join & Leave buttons
    const collector = msg.createMessageComponentCollector({ componentType: ComponentType.Button });

    collector.on("collect", async i => {
        const groupID = i.customId.split("-")[1];
        const group = await Group.findOne({_id: groupID}).populate("captain members game");
        const userDB = await client.findUserById(i.user.id);

        // Rejoindre le groupe
        if (i.customId.split("-")[2] === "join") {
            // Utilisateur non enregistré
            if (!userDB) {
                return await i.reply({
                    content: `${CROSS_MARK} Tu ne peux pas rejoindre le groupe, car tu n'es pas enregistré.\n:arrow_right: Enregistre toi avec la commande \`/register <steamid>\`.`,
                    ephemeral: true,
                });
            }

            // Utilisateur blacklisté
            if (userDB.blacklisted) {
                return await i.reply({
                    content: `${CROSS_MARK} Tu ne peux pas rejoindre le groupe car tu es blacklisté.`,
                    ephemeral: true,
                });
            }

            // Groupe complet
            if (group.nbMax === group.size) {
                return await i.reply({
                    content: `${CROSS_MARK} Tu ne peux pas rejoindre le groupe car celui-ci est complet.`,
                    ephemeral: true,
                });
            }

            // Utilisateur puni
            if (userDB.warning === 3) {
                return await i.reply({
                    content: `${CROSS_MARK} Tu ne peux pas rejoindre le groupe car tu es puni.`,
                    ephemeral: true,
                });
            }

            // Utilisateur déjà dans le groupe
            if (group.members.find(us => us.userId === userDB.userId)) {
                return await i.reply({
                    content: `${CROSS_MARK} Tu ne peux pas rejoindre le groupe car tu es déjà membre.`,
                    ephemeral: true,
                })
            }

            return await joinGroup(client, i.guildId, group, userDB)
        }

        // Quitter le groupe
        if (i.customId.split("-")[2] === "leave") {
            // Le capitaine ne peut pas quitter le groupe
            if (userDB.userId === group.captain.userId) {
                return await i.reply({
                    content: `${CROSS_MARK} Tu ne peux pas quitter le groupe car tu es le capitaine.`,
                    ephemeral: true,
                })
            }

            // Utilisateur hors du groupe
            if (!group.members.find(us => us.userId === userDB.userId)) {
                return await i.reply({
                    content: `${CROSS_MARK} Tu ne peux pas quitter le groupe car tu n'es pas membre.`,
                    ephemeral: true,
                })
            }

            return await leaveGroup(client, i.guildId, group, userDB);
        }
    });
}
```

Ce que j'avais modifié au niveau du collecteur si ça peut aider, pour réduire le nombre d'information a fournir (que tout puisse passer dans le interactionCreate à terme sans contexte de la commande), et j'avais corriger aussi un problème dans les conditions qui étaient fausse pour le capitaine et qui complexifiait la lecture car mis a l'envers (vérification de si tout est vrai puis un par un, plutôt que de tout faire directement un par un qui divise par deux le nombre d'occurrence)

**Comment by Kekwel** [comment]
j'étais justement dessus là, je vais reprendre ton raisonnement

**Comment by 0xN0x** [comment]
D'acc, la regex va peut être peser un peu lourd pour juste ça au final, comme on est (normalement) sûr du nombre d'élément et de comment il est structuré je pense que un split sera plus opti normalement, après je suis pas bien au fait des optimisations coté pré-compilateur sur Node.JS 🤔

**Comment by Kekwel** [comment]
Je te fais confiance là dessus ! Je vais changer utiliser le split
