### ISSUE TITLE
Fonction retryForever inutilisée

### ISSUE THREAD

**Issue by 0xN0x** [Chasseur-de-Succes/CDS-BOT#124]
https://github.com/Chasseur-de-Succes/CDS-BOT/blob/c83dfc3a4c1246bca75f5ee5c62d7bd08f372c0e/util/util.js#L73-L77

Faut-il la supprimer ? Elle est inutilisée en plus d'être potentiellement dangereuse (retryEvery5minutes existe déjà pour le bypass de rate limiter).

**Comment by Kekwel** [comment]
Oui on peut la supprimer, c'était utilisé en lien avec `refreshGames` il me semble, que Rick a enlevé car plus nécessaire (c'était pour initier la récup des jeux via l'api Steam)
