### ISSUE TITLE
Log lors de banissements

### ISSUE THREAD

**Issue by rick-gnous** [Chasseur-de-Succes/CDS-BOT#134]
Les logs ne sont pas envoyés lors d'un banissement et soulève une erreur. Il faut le corriger en remplacant `setAuthor()` par `setTitle()` dans `events/guildBanAdd.js` et `events/guildBanRemove.js`.

**Comment by 0xN0x** [comment]
[`setAuthor`](https://discord.js.org/docs/packages/builders/1.7.0/EmbedBuilder:Class#setAuthor) est bien la bonne fonction, mais elle doit prendre un objet [EmbedAuthorOptions](https://discord-api-types.dev/api/discord-api-types-v10/interface/APIEmbedAuthor) en paramètre et pas 2 paramètres comme c'est le cas actuellement.

```js
.setAuthor(`Membre banni`, ban.user.displayAvatarURL({dynamic: true, size: 4096, format: 'png'}))
```
devient
```js
.setAuthor({
  name: "Membre banni", 
  iconURL: ban.user.displayAvatarURL({dynamic: true, size: 4096, format: 'png'})
})
```

Je vais faire une PR
