### ISSUE TITLE
Affiche date dans les calendriers

### ISSUE THREAD

**Issue by Kekwel** [Chasseur-de-Succes/CDS-BOT#137]
cf https://github.com/Chasseur-de-Succes/CDS-BOT/issues/99

- [x] fix affichage de la date, en utilisant https://hammertime.cyou/fr

EDIT : nouvelle issue pour les commandes admin #145

**Comment by Kekwel** [comment]
pour la commande admin, est-ce qu'on reprend le même affichage que le /calendrier, mais juste avec tous les events ?

**Comment by 0xN0x** [comment]
Pour les timestamp, pour eviter de les écrire à la mieux le mieux est de passé par le formatters de discord.js pour ça : https://discord.js.org/docs/packages/formatters/main/time:Function
```js
const { time } = require('discord.js');
const date = new Date();

const relative = time(date, 't'); // <t:Now:t>
```

**Comment by Kekwel** [comment]
Ah merci !! je connaissais pas !

**Comment by Kekwel** [comment]
J'ai oublié de rajouter le # dans mon commit mais j'ai utilisé `TimestampStyles.ShortTime` plutôt que `'t'`
