### ISSUE TITLE
Création commande admin

### ISSUE THREAD

**Issue by rick-gnous** [Chasseur-de-Succes/CDS-BOT#139]
Suite au fixe #138, on s'est aperçu qu'il n'est pas possible de mettre des permissions sur des sous commandes.
Est-ce qu'on ne ferait pas une commande admin et regrouper les sous commandes (warn par exemple, ainsi que add) dedans ?

**Comment by Kekwel** [comment]
Yes ca sera mieux et plus simple pour les admins je pense

**Comment by rick-gnous** [comment]
migré dans #145
