### ISSUE TITLE
[event] log

### ISSUE THREAD

**Issue by TobiBiotex** [Chasseur-de-Succes/CDS-BOT#31]
Affiche un message de log dans un channel log lors d'un de ces évents : 

- Channel "logs"
- [x] membre qui à rejoint le serv
- [x] membre qui à quitter le serv
- [x] message supprimé (avec le contenu)
- [x] membre ban / unban / kick (membre, modérateur, raison)
- [x] changement de pseudo (sur le serveur)
- Channel "logs-bot"
- [X] log boutique (achat, vente,...)
- [x] give money (add/remove)

**Comment by 0xN0x** [comment]
Comme ban et unban ont été codé, fixé ?

**Comment by rick-gnous** [comment]
Oui en effet
