### ISSUE TITLE
Groupe : valider les joueurs présents

### ISSUE THREAD

**Issue by Kekwel** [Chasseur-de-Succes/CDS-BOT#51]
Suggestion de Tryste : 
Pouvoir valider les joueurs présents aux events

A en discuter

**Comment by 0xN0x** [comment]
Est-ce que ça a été discuté ? A fermé si non d'ici à ce que l'idée soit de nouveau d'actualité ?

**Comment by 0xN0x** [comment]
Non pas de case a cochées, mais il y a moyen d'envoyer un message par joueur qui s'indique comme présent, et le capitaine doit confirmer ou refuser les participations à la limite ?

**Comment by rick-gnous** [comment]
Ça sera relativement lourd , notamment pour les gros groupes qui peuvent atteindre une dizaine de personnes. Il faut réfléchir a la meilleure mise en place, voir checker du côté admin / utilisateur si cela est toujours d'actualité

**Comment by Kekwel** [comment]
Et pourquoi pas un seul message qui est envoyé dans le channel du groupe, avec un bouton "Je serai présent" ?
Et côté validation, le capitaine / admin pourrait avoir un message avec un Select des joueurs qui ont dit être présent, qu'il pourrait cocher (via multi select, il me semble que c'est possible mais pas sûr) ?

Mais oui, voir si c'est toujours d'actualité d'abord !

**Comment by rick-gnous** [comment]
> Et pourquoi pas un seul message qui est envoyé dans le channel du groupe, avec un bouton "Je serai présent" ?

Plutot "je suis présent", mais c'est pas fiable, ou alors on rejette les gens qui sont pas en vocal au moment de cliquer sur le bouton ? ça commence à devenir un peu lourd je trouve 

> Et côté validation, le capitaine / admin pourrait avoir un message avec un Select des joueurs qui ont dit être présent, qu'il pourrait cocher (via multi select, il me semble que c'est possible mais pas sûr) ?

on peut regarder ça, voir si c'est possible. sinon un select tout seul est assez lourd aussi pour le capitaine qui va vite avoir la flemme

> Mais oui, voir si c'est toujours d'actualité d'abord !

demande de confirmation mais cela semble ne plus être d'actualité grâce aux tickets. en cas d'absence trop régulière, c'est remonté aux admins

**Comment by rick-gnous** [comment]
je confirme, ce n'est plus d'actualité
