### ISSUE TITLE
Groupe : ajouter une commande pour voir les prochaines sessions

### ISSUE THREAD

**Issue by Kekwel** [Chasseur-de-Succes/CDS-BOT#55]
Pouvoir afficher de façon chronologique les sessions à venir

**Comment by Kekwel** [comment]
voir pour avoir avoir une / commande possible en MP

**Comment by rick-gnous** [comment]
Est-ce #99 ne répondrait pas a cette question ?

**Comment by Kekwel** [comment]
Exact !
