### ISSUE TITLE
Éviter au max les MP

### ISSUE THREAD

**Issue by Kekwel** [Chasseur-de-Succes/CDS-BOT#75]
Faire un channel "feed" ou directement dans #bots afin d'éviter les MP intempestifs (sauf pour rappel event) : 

- Montée de niveau
- Passage d'écuyer à chasseur
- autres ?

**Comment by rick-gnous** [comment]
Peut-être faire un gros refactor des messages pour rejoindre les groupes avec les boutons. Ça permettra de limiter les MPs en cas d'erreur avec le groupe (comme [ici](https://stackoverflow.com/questions/69805973/send-an-ephemeral-message-to-person-who-clicked-button)) ainsi que d'avoir un affichage plus propre. A voir si on ne peut pas étendre ça à d'autres interactions.

Si ça te semble ok, on peut faire un ticket pour ce refactor.

**Comment by Kekwel** [comment]
Ca me va oui ! Je suis sur qu'il y a moyen de mieux faire de ce côté. On peut en faire un ticket

**Comment by rick-gnous** [comment]
J'essayerai de faire une liste des fonctionnalités faisant des MPs et on pourra ensuite voir ce qu'on garde et ce qu'on vire, sinon ce ticket va pouvoir rester ouvert longtemps

**Comment by rick-gnous** [comment]
cf. #141
