### ISSUE TITLE
Channel log

### ISSUE THREAD

**Issue by rick-gnous** [Chasseur-de-Succes/CDS-BOT#9]
À définir avec une commande

**Comment by TobiBiotex** [comment]
Pour définir le channel, on passe par une commande "config log <mention channel>" ? Avec vérification que le bot peut le lire et écrire
Je me dit l'avantage de passé par une commande config ça permettrais de pouvoir rajouter d'autre type de config plus tard

et dans la bdd on créé une table config ? Mais pour les sous données là j'ai pas d'idée de comment faire

**Comment by 0xN0x** [comment]
Fixé avec `/salon logs` ?

**Comment by rick-gnous** [comment]
Normalement. A réouvrir si on s'aperçoit d'une boulette
