### ISSUE TITLE
Bug: /group create avec max si pas un nombre

### ISSUE THREAD

**Issue by TobiBiotex** [Chasseur-de-Succes/CDS-BOT#93]
Ajout d'une vérification lors de l'exécution de la commande : **/group create** avec un nombre max de participants que le nombre soit bien un nombre
Log : 18/05/2023
```
/home/container/node_modules/mongoose/lib/document.js:2782
    this.$__.validationError = new ValidationError(this);
                               ^

ValidationError: Group validation failed: nbMax: Cast to Number failed for value "2 joueurs" (type string) at path "nbMax"
```

**Comment by Kekwel** [comment]
c'est fix du coup
![image](https://github.com/Chasseur-de-Succes/CDS-BOT/assets/9060357/43fe43f4-dded-405f-86e3-4d7d64f53cb3)
