### ISSUE TITLE
Calendrier des disponibilités

### ISSUE THREAD

**Issue by Kekwel** [Chasseur-de-Succes/CDS-BOT#99]
Idée de Sqweeb :

> j'aimerai que le bot puisse envoyer une sorte de calendrier de la semaine complet à chaque personne qui ont des évents. Chaque Lundi hop le calendrier pop la personne voit les events, les dates et heure de la semaine. Comme ça il aura plus de faciliter à voir les dispo pour la semaine. Et si il en rajoute sa se rajoute sur le calendrier, le bot en fait un nouveau ou ça change automatiquement, pareil si il l'event est supprimé

> J'aimerai qu'il soit comme ça 

```
Lundi               Mardi               Mercredi                 Jeudi                         Vendredi               Samedi                  Dimanche

17h 18h                                      21h                              13h                                                              15h30
Cyberpunk                               hell let loose            smite                                                           Binary
```

> Ou alors qu'il envoie un /calendar au bot et le bot lui envoie son calendrier

**Comment by Kekwel** [comment]
un groupe se fait, je m'inscrit dessus.
Le proprio mets une date
Pop up du calendrier dans les mp pour montrer la date et l'heure

J'ai oublié si j'ai un event tel jour 
commande /calendar en mp au bot
le calendrier s'affiche

Commande admin pour avoir un calendrier avec l'ensemble des groupes

**Comment by Kekwel** [comment]
ca avance trkl
![image](https://github.com/Chasseur-de-Succes/CDS-BOT/assets/9060357/e270bd54-4a32-4dbe-acc7-77e30e783258)

- [x] créer la commande /calendrier
    - [ ] ajout d'un paramètre pour sélectionner la semaine voulu
- [x] récup date du lundi et du dimanche sur la semaine courante
- [x] récup des events compris entre ces 2 dates
    - [ ] remplir l'embed avec le bon jour et le bon jeu
- [x] créer le squelette de l'embed
    - [ ] ajouter 2 boutons pour semaine précédente et semaine suivante

**Comment by Kekwel** [comment]
et vive les dates en JS

**Comment by Kekwel** [comment]
- [ ] Commande admin pour avoir un calendrier avec l'ensemble des groupes

**Comment by Kekwel** [comment]
il faut changer l'affichage de l'heure, ptete en utilisant cette syntaxe https://hammertime.cyou/fr
![image](https://github.com/Chasseur-de-Succes/CDS-BOT/assets/9060357/20e2a52a-e24c-4bbd-b457-f5eaf4c5b47d)

**Comment by rick-gnous** [comment]
peut-être faire un ticket à côté ou le mettre dans la liste des choses à faire avec la commande admin ?

**Comment by Kekwel** [comment]
je vais faire un nouveau ticket regroupant ces 2 choses (commande admin + fix horaire), ce ticket est terminé pour moi
